In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data=pd.read_excel('Coeur.xlsx')

In [3]:
#2. Faites une copie de l’objet “data” dans un nouvel objet appelé “df”.
df = data.copy()
df.head()

AGE   SEXE  TDT  PAR  CHOLESTEROL  GAJ     ECG  FCMAX ANGINE  DEPRESSION   \
0   40  homme   AA  140          289    0  Normal    172    Non          0.0   
1   49  femme  DNA  160          180    0  Normal    156    Non          1.0   
2   37  homme   AA  130          283    0      ST     98    Non          0.0   
3   48  femme  ASY  138          214    0  Normal    108    Oui          1.5   
4   54  homme  DNA  150          195    0  Normal    122    Non          0.0   

       PENTE  CŒUR  
0  Ascendant     0  
1       Plat     1  
2  Ascendant     0  
3       Plat     1  
4  Ascendant     0

# verifier les doublons

In [4]:
df.duplicated().sum()

0

# Supprimer les doublons


In [5]:
    df.drop_duplicates()

AGE   SEXE  TDT  PAR  CHOLESTEROL  GAJ     ECG  FCMAX ANGINE  \
0     40  homme   AA  140          289    0  Normal    172    Non   
1     49  femme  DNA  160          180    0  Normal    156    Non   
2     37  homme   AA  130          283    0      ST     98    Non   
3     48  femme  ASY  138          214    0  Normal    108    Oui   
4     54  homme  DNA  150          195    0  Normal    122    Non   
..   ...    ...  ...  ...          ...  ...     ...    ...    ...   
913   45  homme   AT  110          264    0  Normal    132    Non   
914   68  homme  ASY  144          193    1  Normal    141    Non   
915   57  homme  ASY  130          131    0  Normal    115    Oui   
916   57  femme   AA  130          236    0     LVH    174    Non   
917   38  homme  DNA  138          175    0  Normal    173    Non   

     DEPRESSION       PENTE  CŒUR  
0            0.0  Ascendant     0  
1            1.0       Plat     1  
2            0.0  Ascendant     0  
3            1.5       Plat     1  
4            0.0  Ascendant     0  
..           ...        ...   ...  
913          1.2       Plat     1  
914          3.4       Plat     1  
915          1.2       Plat     1  
916          0.0       Plat     1  
917          0.0  Ascendant     0  

[918 rows x 12 columns]

# Verification de contantes

In [6]:
import math
b = math.nan
print(np.isnan(b))


True


# Verification de donnée manquantes

In [7]:
df.isna().sum()

AGE            0
SEXE           0
TDT            0
PAR            0
CHOLESTEROL    0
GAJ            0
ECG            0
FCMAX          0
ANGINE         0
DEPRESSION     0
PENTE          0
CŒUR           0
dtype: int64

# Normalisation de toutes les variables quantitatives


In [8]:
df_quant =df.select_dtypes(exclude='object').drop('CŒUR' , axis=1)

In [9]:
df_quant =df.select_dtypes(exclude='object').drop('CŒUR' , axis=1).columns
for col in df_quant:
    df[col]=pd.DataFrame(df[col]/df[col].mean())
df_norm =df[df_quant]
df_norm

AGE       PAR  CHOLESTEROL      GAJ     FCMAX  DEPRESSION 
0    0.747511  1.057430     1.453726  0.00000  1.257224     0.000000
1    0.915701  1.208491     0.905435  0.00000  1.140273     1.126933
2    0.691448  0.981899     1.423544  0.00000  0.716325     0.000000
3    0.897014  1.042324     1.076461  0.00000  0.789420     1.690400
4    1.009140  1.132960     0.980887  0.00000  0.891752     0.000000
..        ...       ...          ...      ...       ...          ...
913  0.840950  0.830838     1.327971  0.00000  0.964846     1.352320
914  1.270769  1.087642     0.970827  4.28972  1.030631     3.831574
915  1.065204  0.981899     0.658955  0.00000  0.840586     1.352320
916  1.065204  0.981899     1.187125  0.00000  1.271843     0.000000
917  0.710136  1.042324     0.880284  0.00000  1.264533     0.000000

[918 rows x 6 columns]

# Recodage de toutes les variables quantitative

In [10]:
def recoder(serie):
  return serie.astype('category').cat.codes


In [11]:
def recoder_df(data):
    for col in data.select_dtypes('object').columns:
        data[col]=recoder(data[col])
        return data
 

In [18]:
recoder_df(df)

AGE  SEXE  TDT       PAR  CHOLESTEROL      GAJ  ECG     FCMAX  \
0    0.747511     1    0  1.057430     1.453726  0.00000    1  1.257224   
1    0.915701     0    3  1.208491     0.905435  0.00000    1  1.140273   
2    0.691448     1    0  0.981899     1.423544  0.00000    2  0.716325   
3    0.897014     0    1  1.042324     1.076461  0.00000    1  0.789420   
4    1.009140     1    3  1.132960     0.980887  0.00000    1  0.891752   
..        ...   ...  ...       ...          ...      ...  ...       ...   
913  0.840950     1    2  0.830838     1.327971  0.00000    1  0.964846   
914  1.270769     1    1  1.087642     0.970827  4.28972    1  1.030631   
915  1.065204     1    1  0.981899     0.658955  0.00000    1  0.840586   
916  1.065204     0    0  0.981899     1.187125  0.00000    0  1.271843   
917  0.710136     1    3  1.042324     0.880284  0.00000    1  1.264533   

     ANGINE  DEPRESSION   PENTE  CŒUR  
0         0     0.000000      0     0  
1         0     1.126933      2     1  
2         0     0.000000      0     0  
3         1     1.690400      2     1  
4         0     0.000000      0     0  
..      ...          ...    ...   ...  
913       0     1.352320      2     1  
914       0     3.831574      2     1  
915       1     1.352320      2     1  
916       0     0.000000      2     1  
917       0     0.000000      0     0  

[918 rows x 12 columns]

# 8-separer la variable cible coeur des autres variables de df

In [28]:
Y=df[['CŒUR']]
X=df[['AGE','SEXE','TDT','PAR','CHOLESTEROL','GAJ','ECG','FCMAX','ANGINE','DEPRESSION ','PENTE']]
X

AGE  SEXE  TDT       PAR  CHOLESTEROL      GAJ  ECG     FCMAX  \
0    0.747511     1    0  1.057430     1.453726  0.00000    1  1.257224   
1    0.915701     0    3  1.208491     0.905435  0.00000    1  1.140273   
2    0.691448     1    0  0.981899     1.423544  0.00000    2  0.716325   
3    0.897014     0    1  1.042324     1.076461  0.00000    1  0.789420   
4    1.009140     1    3  1.132960     0.980887  0.00000    1  0.891752   
..        ...   ...  ...       ...          ...      ...  ...       ...   
913  0.840950     1    2  0.830838     1.327971  0.00000    1  0.964846   
914  1.270769     1    1  1.087642     0.970827  4.28972    1  1.030631   
915  1.065204     1    1  0.981899     0.658955  0.00000    1  0.840586   
916  1.065204     0    0  0.981899     1.187125  0.00000    0  1.271843   
917  0.710136     1    3  1.042324     0.880284  0.00000    1  1.264533   

     ANGINE  DEPRESSION   PENTE  
0         0     0.000000      0  
1         0     1.126933      2  
2         0     0.000000      0  
3         1     1.690400      2  
4         0     0.000000      0  
..      ...          ...    ...  
913       0     1.352320      2  
914       0     3.831574      2  
915       1     1.352320      2  
916       0     0.000000      2  
917       0     0.000000      0  

[918 rows x 11 columns]

# 9. En utilisant la fonction train_test_split du module model_selection du package sklearn, subdiviser vos données X et Y en respectivement X_train, X_test et Y_train, Y_test. X_train et Y_train doivent contenir respectivement 80 % des données de X et Y.

In [29]:
from sklearn.model_selection import train_test_split


In [30]:
X_train, X_test, y_train, y_test= train_test_split (X,Y,test_size =0.2 ,random_state = 1)

In [31]:
print('train_set', X_train.shape)
print('test_set', X_test.shape)

train_set (734, 11)
test_set (184, 11)


# 10. En utilisant la classe LogisticRegression du module linear_model du package sklearn, construisez un modèle de régression logistique en utilisant les données X_train et Y_train et la méthode fit de la classe LogisticRegression.

In [32]:
from sklearn.linear_model import LogisticRegression

In [34]:
logReg = LogisticRegression()
logReg.fit(X_train, y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

# 11- Affichage de la probabilité d'appartenance à chacune des classes de la variable coeur


In [35]:
logReg.predict_proba(X_test[:5])

array([[0.32777726, 0.67222274],
       [0.17504272, 0.82495728],
       [0.03672641, 0.96327359],
       [0.08969688, 0.91030312],
       [0.23290901, 0.76709099]])

# 12- Prediction de la classe d'appartenance de chaque individu de X_test


In [40]:
y_pred= logReg.predict(X_test)
y_pred


array([1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

#  confusion_matrix

In [37]:
from sklearn.metrics import confusion_matrix

In [39]:
matrix= confusion_matrix(y_pred, y_test)

In [41]:
matrix

array([[ 66,   8],
       [  8, 102]], dtype=int64)

# accuracy_score

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
accur= accuracy_score(y_pred, y_test)
accur

0.9130434782608695

# recall_score

In [45]:
from sklearn.metrics import recall_score

In [46]:
recall= recall_score(y_pred, y_test)
recall

0.9272727272727272

#  precision_score 

In [47]:
from sklearn.metrics import precision_score

In [48]:
pre= precision_score(y_pred, y_test)
pre

0.9272727272727272